### PR TITLE
Extend usage and use markercluster

### PR DESCRIPTION
**Pull request by abrahammartin**
https://github.com/SmartCambridge/BusStopChooser/commit/62f90d2065fd9e6acf361e12f95345090271a135 uses markerCluster to make map rendering faster. leaflet is very slow when processing multiple markers on the screen, use markerClusterGroup, which aggregate markers into clusters, making it faster.
https://github.com/SmartCambridge/BusStopChooser/commit/bdd0436dc1023f5e63a1c6c91af1b6ec2d696fe3 Provides an alternative on_click event. The default on_click event allows user to select single or multiple bus stops. Extend the functionality of the BusStopChooser by providing an alternative on_click event to the default one that will redirect the user to the bus stop web app endpoint. This can be controlled by the param option onclick_redirect.
https://github.com/SmartCambridge/BusStopChooser/pull/6/commits/b0d648719a0d0ede8eb5720f5925d5f16bbbc7d4 bugfix

### CODE REVIEW

**Review by jw35 — DISMISSED** [review]
The onclick change as written would be the only tie between BusStopChooser and tfc_web, which would be a shame. It's also limited to targeting '/transport/stop/'.

I suggest replacing 'onclick_redirect' with a parameter supplying a callback which if present and defined (c.f. stops_callback) will be called whenever a stop is clicked and which receives the stop as a parameter. For the current tfc_web case this callback could issue the redirect to '/transport/stop/'.

While you are at it, could you fix the mess I've made of the delimiter in the documentation for 'location' and 'stops_callback' so they render correctly (swap ':' for '|')? Ta.

**Comment by jw35** [comment]
Might be worth setting 'disableClusteringAtZoom' to 18 or 19 so that pairs of stops, and stops in Drummer Street un-cluster at max or almost-max zoom. Without this, you need to know that you can click on the cluster to get it to 'spiderify' which isn't obvious and still results in the stops displaying in the wrong places.

**Comment by jw35** [comment]
Oh, and this change breaks demo.html which is doing to need markerCluster's library loaded.

**Comment by jw35** [comment]
> I suggest replacing 'onclick_redirect' with a parameter supplying a callback which if present and defined (c.f. stops_callback) will be called whenever a stop is clicked and which receives the stop as a parameter. For the current tfc_web case this callback could issue the redirect to '/transport/stop/'.

Even better, call it with the stop *and* an indication of whether the stop is being added or removed, assuming that's not too hard to do. That way this callback an be used for all sorts of interesting things as well as just issuing a redirect on click.

**Comment by ijl20** [comment]
The need for a callback on 'stop click' has cropped up before but not involving a redirect, so I suggest Jon's suggestion is the correct one, e.g. an additional optional param "stop_click_callback" from the outer page which in Abraham's reqt would simply be function () { location.href = NEW_URL }.

**Comment by abrahammartin** [comment]
> Might be worth setting 'disableClusteringAtZoom' to 18 or 19 so that pairs of stops, and stops in Drummer Street un-cluster at max or almost-max zoom. Without this, you need to know that you can click on the cluster to get it to 'spiderify' which isn't obvious and still results in the stops displaying in the wrong places.

True, but will this avoid having stops that are unclickable because they are on top of each other (I think we found an example the other day)?

**Comment by jw35** [comment]
I think the example we saw was because I had some duplicated stops. I’ve never *seen* more than one stop with the same position. A suitable query on the stop table could answer the question.

Jon

--
Jon Warbrick

On 22 Jan 2019, at 21:44, Abraham Martin <notifications@github.com<mailto:notifications@github.com>> wrote:


True, but will this avoid having stops that are unclickable because they are on top of each other (I think we found an example the other day)?

**Review by jw35 — APPROVED** [review]

**Pull request merged**
